# Generated by Django 6.0.5 on 2026-05-13 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_customuser_id'),
        ('register', '0002_book_borrowedbook'),
    ]

    operations = [
    ]
